version: '3.9'

services:
  db:
    image: mysql:8.0
    container_name: db
    restart: always
    environment:
      MYSQL_DATABASE: seu_banco
      MYSQL_USER: seu_usuario
      MYSQL_PASSWORD: sua_senha
      MYSQL_ROOT_PASSWORD: root_senha
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  web:
    build: .
    container_name: web
    command: sh -c "apt-get update && apt-get install -y netcat && ./wait-for-db.sh && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  db_data:
