version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: railway
      MYSQL_ROOT_PASSWORD: rRdPwfgCbwgVQLMNPUUwvZbWxqPwHOIgk
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  web:
    build: .
    depends_on:
      - db
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      MYSQL_HOST: db
      MYSQL_DATABASE: railway
      MYSQL_USER: root
      MYSQL_PASSWORD: rRdPwfgCbwgVQLMNPUUwvZbWxqPwHOIgk
      MYSQL_PORT: "3306"
    command: >
      bash -c "
        python manage.py migrate &&
        python manage.py collectstatic --noinput &&
        gunicorn EstEsc.wsgi:application --bind 0.0.0.0:8000
      "

volumes:
  db_data:
