version: '3.9'

services:
  db:
    image: mysql:8.0
    container_name: db
    restart: always
    environment:
      MYSQL_DATABASE: seu_banco
      MYSQL_USER: seu_usuario
      MYSQL_PASSWORD: sua_senha
      MYSQL_ROOT_PASSWORD: root_senha
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  web:
    build: .
    container_name: web
    command: ["./wait-for-db.sh", "gunicorn", "seu_projeto.wsgi:application", "--bind", "0.0.0.0:8000"]
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  db_data:
